Refatoring api
TeangaNLP/cardamom-workbench pull request #16
Opened 2024-07-10 19:43 UTC by K03Rat

2024-07-11 08:59 UTC, jmccrae requested changes

2024-07-11 08:59 UTC, jmccrae commented on webserver/repositories/userRepository.py
> +        self.session.flush()
no `session.commit()`?

2024-07-11 08:59 UTC, jmccrae commented on webserver/repositories/userRepository.py
> +        print(email)
Avoid leaving println debugging in final code. Remove or change to logging

2024-07-11 08:59 UTC, jmccrae commented on webserver/utilities.py
> +    return {k: v for k, v in model.__dict__.items() if not k.startswith("_")}
Duplicate of method in `posService.py`?

2024-07-11 08:59 UTC, jmccrae commented on webserver/utilities.py
> +def serialise(model):
This method's name is to general and does not do what it says (it doesn't write anything to disk)

2024-08-01 15:13 UTC, AdeDoyle commented
`docker compose build` breaks with error: `ModuleNotFoundError: No module named 'services.fileService'` @banerjeeshubhanker

2024-08-09 14:49 UTC, merged